"""List block handler.

Renders ``type: list`` blocks as native Word numbered/bulleted lists using
OOXML ``abstractNum`` + ``num`` definitions in ``numbering.xml``.  Each
paragraph receives a ``w:numPr`` element so Word treats it as a proper
list item — the marker is generated by Word, TOC/accessibility tools see
it correctly, and the document round-trips cleanly.

GOST indentation:
    marker (``–`` or ``1)``) at 1.25 cm from text margin  →  709 twips
    text continuation at 1.75 cm                          →  992 twips
    hanging = 0.5 cm                                       →  283 twips

Supported styles:
    bullet  — em-dash bullet (``–``), GOST-recommended marker character.
    numeric — decimal numbering with ``1)``, ``2)`` … format.
"""

from pathlib import Path

from docx.oxml import OxmlElement
from docx.oxml.ns import qn

from ._base import RenderContext

# GOST list indentation in twips (1 cm ≈ 566.93 twips)
_LEFT_TWIPS = 992    # 1.75 cm — where continuation lines start
_HANG_TWIPS = 283    # 0.50 cm — hanging, so marker sits at 1.25 cm

_NUM_FORMAT = {"bullet": "bullet", "numeric": "decimal"}
_LEVEL_TEXT = {"bullet": "–",     "numeric": "%1)"}


class ListHandler:
    """Handler for ``type: list`` blocks."""

    def validate(self, block: dict, index: int, base_dir: Path) -> dict:
        """Validate a list block and return its normalised form.

        Args:
            block: Raw dict with ``style`` and ``items`` keys.
            index: 1-based position in the content list (for error messages).
            base_dir: Config file directory (unused for lists).

        Returns:
            Normalised block dict with ``type``, ``style``, and ``items``.

        Raises:
            ValueError: If ``style`` is not ``"bullet"`` or ``"numeric"``,
                or if ``items`` is missing, empty, or contains non-strings.
        """
        style = block.get("style")
        items = block.get("items")

        if style not in ("bullet", "numeric"):
            raise ValueError(
                f"content[{index}]: list.style должен быть 'bullet' или 'numeric', "
                f"получено: {style!r}"
            )

        if not isinstance(items, list) or not items:
            raise ValueError(
                f"content[{index}]: list.items обязателен и должен быть непустым списком"
            )

        for i, item in enumerate(items, start=1):
            if not isinstance(item, str) or not item.strip():
                raise ValueError(
                    f"content[{index}]: list.items[{i}] должен быть непустой строкой"
                )

        return {
            "type": "list",
            "style": style,
            "items": [item.strip() for item in items],
        }

    def render(self, doc, block: dict, ctx: RenderContext) -> None:
        """Render each list item as a native Word list paragraph.

        A single ``abstractNum``/``num`` definition is created for the whole
        block; all items share the same ``numId`` so Word numbers them as one
        continuous list.
        """
        num_id = _add_list_definition(doc, block["style"])
        for item in block["items"]:
            paragraph = doc.add_paragraph(item, style="GOST List")
            _apply_num_pr(paragraph, num_id)
        ctx.current_page_has_content = True


# ---------------------------------------------------------------------------
# Private helpers
# ---------------------------------------------------------------------------

def _ensure_numbering_element(doc):
    """Return the root ``w:numbering`` XML element, creating the part if absent."""
    try:
        return doc.part.numbering_part._element
    except KeyError:
        from docx.parts.numbering import NumberingPart
        from docx.opc.constants import RELATIONSHIP_TYPE as RT
        numbering_part = NumberingPart.new()
        doc.part.relate_to(numbering_part, RT.NUMBERING)
        return numbering_part._element


def _add_list_definition(doc, style: str) -> int:
    """Add an ``abstractNum`` + ``num`` pair for *style* and return the ``numId``.

    Each call adds a fresh definition so independent list blocks restart their
    counter independently.  If the same ``numId`` were reused across blocks
    Word would continue the count from where the previous block left off.
    """
    numbering = _ensure_numbering_element(doc)

    # abstractNumId = count of existing abstractNum elements
    existing_abstract = numbering.findall(qn("w:abstractNum"))
    abstract_num_id = len(existing_abstract)

    abstract_num = _build_abstract_num(abstract_num_id, style)

    # abstractNum elements must appear before num elements
    first_num = numbering.find(qn("w:num"))
    if first_num is not None:
        first_num.addprevious(abstract_num)
    else:
        numbering.append(abstract_num)

    # numId = count of existing num elements + 1  (numId 0 is reserved)
    existing_nums = numbering.findall(qn("w:num"))
    num_id = len(existing_nums) + 1

    num = OxmlElement("w:num")
    num.set(qn("w:numId"), str(num_id))
    abstract_num_id_ref = OxmlElement("w:abstractNumId")
    abstract_num_id_ref.set(qn("w:val"), str(abstract_num_id))
    num.append(abstract_num_id_ref)
    numbering.append(num)

    return num_id


def _build_abstract_num(abstract_num_id: int, style: str):
    """Build and return a ``w:abstractNum`` element for *style* at level 0."""
    abstract_num = OxmlElement("w:abstractNum")
    abstract_num.set(qn("w:abstractNumId"), str(abstract_num_id))

    multi = OxmlElement("w:multiLevelType")
    multi.set(qn("w:val"), "singleLevel")
    abstract_num.append(multi)

    lvl = OxmlElement("w:lvl")
    lvl.set(qn("w:ilvl"), "0")

    start = OxmlElement("w:start")
    start.set(qn("w:val"), "1")
    lvl.append(start)

    num_fmt = OxmlElement("w:numFmt")
    num_fmt.set(qn("w:val"), _NUM_FORMAT[style])
    lvl.append(num_fmt)

    lvl_text = OxmlElement("w:lvlText")
    lvl_text.set(qn("w:val"), _LEVEL_TEXT[style])
    lvl.append(lvl_text)

    lvl_jc = OxmlElement("w:lvlJc")
    lvl_jc.set(qn("w:val"), "left")
    lvl.append(lvl_jc)

    # Indentation: marker at 1.25 cm, text continuation at 1.75 cm
    p_pr = OxmlElement("w:pPr")
    ind = OxmlElement("w:ind")
    ind.set(qn("w:left"), str(_LEFT_TWIPS))
    ind.set(qn("w:hanging"), str(_HANG_TWIPS))
    p_pr.append(ind)
    lvl.append(p_pr)

    # Run properties: Times New Roman 14 pt
    r_pr = OxmlElement("w:rPr")
    r_fonts = OxmlElement("w:rFonts")
    for attr in ("w:ascii", "w:hAnsi", "w:cs", "w:eastAsia"):
        r_fonts.set(qn(attr), "Times New Roman")
    r_pr.append(r_fonts)
    for tag in ("w:sz", "w:szCs"):
        sz = OxmlElement(tag)
        sz.set(qn("w:val"), "28")   # 14 pt × 2 half-points
        r_pr.append(sz)
    lvl.append(r_pr)

    abstract_num.append(lvl)
    return abstract_num


def _apply_num_pr(paragraph, num_id: int, ilvl: int = 0) -> None:
    """Attach a ``w:numPr`` element to *paragraph* referencing *num_id*."""
    p_pr = paragraph._p.get_or_add_pPr()

    num_pr = OxmlElement("w:numPr")

    ilvl_elem = OxmlElement("w:ilvl")
    ilvl_elem.set(qn("w:val"), str(ilvl))
    num_pr.append(ilvl_elem)

    num_id_elem = OxmlElement("w:numId")
    num_id_elem.set(qn("w:val"), str(num_id))
    num_pr.append(num_id_elem)

    # numPr must be the first child of pPr
    p_pr.insert(0, num_pr)
